### PR TITLE
Initial set up

### PR DESCRIPTION
**Pull request by tiagomarin**
### ps. I was alone this week
**run ``rails db:reset`` to run the seed file and populate the application if you want**

### :heavy_check_mark: - Login page and registration page:
- Should be built with Devise.
### :heavy_check_mark: - Food list:
- Should display a list of food added by the logged-in user as in the wireframe (for teams with only 2 people - display also quantity of a given food).
- Should lead to a form that allows users to add new food.
### :heavy_check_mark: - Recipes list:
- Should display a list of recipes created by the logged-in user as in the wireframe.
- Should lead to recipe details.
- If the user is the owner of the recipe, should allow the user to delete it.
### :heavy_check_mark: - Public recipe list:
- Should display a list of all public recipes ordered by newest as in the wireframe.
- Should lead to recipe details.
### :heavy_check_mark: - Recipe details:
- If the recipe is public or the user is the owner of the recipe, should display the recipe details as in the wireframe.
- If the user is the owner of the recipe, should lead to the form that allows the user to add new food.
### :heavy_check_mark: - General shopping list view (**only for a group that has less than 3 members**):
- Should show the list of food that is missing for all recipes of the logged-in user (compare the list of food for all recipes with the general food list of that user).
- Should count the total food items and total price of the missing food.
### :speech_balloon: Feel free to shoot me a message in the pull request if you have any questions.

Thank you for your time!

### CODE REVIEW

**Review by BenMukebo — COMMENTED** [review]
## STATUS: INVALID ❌ 

Hi  @tiagomarin,

I can't miss felicitating your efforts and energy, you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 



- [ ] You have submitted a project, that did not follow the Git flow.
- The pull request link that you should have submited should be opened from the dev branch into the main branch and include all the changes

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@BenMukebo) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit.

**Comment by tiagomarin** [comment]
Hi @BenMukebo 👋 

Thanks for the attempt to review my code, sorry for that, I forgot about this.

I can't submit again the button doesn't work! I have a new pull request:

https://github.com/tiagomarin/Best-Recepies/pull/13

**Comment by BenMukebo** [comment]
Hello @tiagomarin, Do you still can't submit the PR ?

**Comment by tiagomarin** [comment]
Hey @BenMukebo, yes I could do it, and the code reviewer rejected again due to git flow but wasn't very specific about it. What should I do? I'm alone this week I guess he didn't see that and invalidated because I don't have PR reviews. I don't know, I'm lost.

**Pull request closed without merging**
